In [6]:
%load_ext autoreload
%autoreload 2
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime
import loganalisis
from glob import glob
import os

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [7]:
#Jueves
diasA1=[datetime(2024,9,26),
      datetime(2024,10,3),
      datetime(2024,10,10),
      datetime(2024,10,17),
      datetime(2024,10,24),
      datetime(2024,10,31),
      datetime(2024,11,7),
      datetime(2024,11,14),
      datetime(2024,11,21),
      datetime(2024,11,28),
      datetime(2024,12,12),
      datetime(2024,12,19),
      datetime(2025,1,9)]

#Viernes
diasA2=[datetime(2024,9,27),
      datetime(2024,10,4),
      datetime(2024,10,11),
      datetime(2024,10,18),
      datetime(2024,10,25),
      datetime(2024,11,8),
      datetime(2024,11,15),
      datetime(2024,11,22),
      datetime(2024,11,29),
      datetime(2024,12,5),# Es un jueves permiutado
      datetime(2024,12,13),
      datetime(2024,12,20),
      datetime(2025,1,10)]

#Martes
diasA3=[datetime(2024,9,24),
      datetime(2024,10,1),
      datetime(2024,10,15),
      datetime(2024,10,22),
      datetime(2024,10,29),
      datetime(2024,11,5),
      datetime(2024,11,12),
      datetime(2024,11,19),
      datetime(2024,11,26),
      datetime(2024,12,3),
      datetime(2024,12,10),
      datetime(2024,12,17),
      datetime(2025,1,7)]
horario=[17,20]
excluidos=["profesor", "clase"]

In [8]:
ficheros = glob("/srv/log/users/*.log")
print(len(ficheros))

45

In [9]:
hoy = datetime.now().date()

tabladict={}
for f in ficheros:
    usuario=os.path.basename(f).replace(".log","")
    if usuario in excluidos :
        continue
    res=loganalisis.asistencia(f,diasA2,horario)
    hasta_hoy={}
    for k,v in res.items():
        if k > hoy:
            continue
        hasta_hoy[k]=v
    serie=pd.Series(hasta_hoy)    
    tabladict[usuario]=serie
    #print(usuario,hasta_hoy)
df=pd.DataFrame(tabladict).T

df=df.sort_index()

In [10]:
df

          2024-09-27  2024-10-04
allirtap           0           0
arobsal            0           0
atabgar            0           0
avaiksn            0           0
azabolo            0           0
balbben            0           0
bfercol1           0           0
cbencan            0           0
cclabot            0           0
cferalo            0           0
cgimmat            0           0
dcamrui            0           0
ddielaf            0           0
dji                0           0
dsorcol            0           0
fbegbeg            0           0
gargagu            0           0
gmuoqui            0           0
gpagchi            0           0
gvidtar            0           0
igompic            0           0
jcresub            0           0
jperalv            0           0
klaskev            0           0
mastoica           0           0
mgardia            0           0
nchudic            0           0
ngomtro            0           0
nherrub            0           0
nterala            0           0
pbosram            0           0
pferrui            0           0
pgarmar5           0           0
ppalmed            0           0
rfguelop           0           0
rjimalb            0           0
sdiamen            0           0
slin3              0           0
solilop            0           0
sripcig           28           0
vpercol            0           0
xhu2               0           0
ytarrui            0           0