In [1]:
import pandas as pd
import glob
import os
from pathlib import Path

In [2]:
homedir=os.getenv("HOME")
notasdir=os.path.join(homedir,'Curso/notas')
notas_limpias_dir=os.path.join(homedir,'Curso/notas_limpias')
print(notasdir,notas_limpias_dir)
#Path.mkdir(notas_limpias_dir,parents=True,exist_ok=True)

/home/profesor/Curso/notas /home/profesor/Curso/notas_limpias

In [3]:
lista=os.path.join(homedir,"listaSS_2024.csv")
dflista=pd.read_csv(lista,delimiter=",",header=None,encoding='latin1')
dflista.columns=['Apellidos','Nombre','DNI','E-mail']
dflista.index=dflista["E-mail"]

dflista=dflista['DNI']
#print(dflista)

tabla={}
emails=[]
for index,val in dflista.items():
    #print(index)
    tabla[index]=val
    emails.append(index)
    
emails.sort()
print(emails)

['abodbro@teleco.upv.es', 'acammor1@teleco.upv.es', 'agomrui1@teleco.upv.es', 'aguialf@teleco.upv.es', 'aibacol@teleco.upv.es', 'ajimcas@edificacion.upv.es', 'alanbas@teleco.upv.es', 'alifriv@teleco.upv.es', 'allirtap@teleco.upv.es', 'allovil2@teleco.upv.es', 'amaresp2@teleco.upv.es', 'amiqfus@teleco.upv.es', 'aperlop2@teleco.upv.es', 'arobsal@teleco.upv.es', 'asancan2@teleco.upv.es', 'atabgar@teleco.upv.es', 'avaiksn@teleco.upv.es', 'azabolo@teleco.upv.es', 'balbben@teleco.upv.es', 'bfercol1@teleco.upv.es', 'cbencan@teleco.upv.es', 'cclabot@teleco.upv.es', 'ccosmir@teleco.upv.es', 'cferalo@teleco.upv.es', 'cgimmat@teleco.upv.es', 'clinche@teleco.upv.es', 'cmolcas@teleco.upv.es', 'dcamrui@teleco.upv.es', 'ddielaf@teleco.upv.es', 'dji@teleco.upv.es', 'dmillyu@teleco.upv.es', 'dnuesal@teleco.upv.es', 'dsorcol@ade.upv.es', 'dtavgra@teleco.upv.es', 'dtoribo@teleco.upv.es', 'fbegbeg@teleco.upv.es', 'fcargra@teleco.upv.es', 'fjgombaq@teleco.upv.es', 'gargagu@teleco.upv.es', 'gchiort@teleco.upv.es', 'gmuoqui@epsg.upv.es', 'gpagchi@etsinf.upv.es', 'grammol@teleco.upv.es', 'gvidtar@teleco.upv.es', 'iborroi@teleco.upv.es', 'idiadol@teleco.upv.es', 'iferjua@teleco.upv.es', 'igompic@teleco.upv.es', 'jcebmir@teleco.upv.es', 'jconara@teleco.upv.es', 'jcotmar@teleco.upv.es', 'jcresub@teleco.upv.es', 'jllotor@teleco.upv.es', 'jmgomalm@teleco.upv.es', 'jperalv@teleco.upv.es', 'jsertob@teleco.upv.es', 'jvalrod@teleco.upv.es', 'jvilsel@teleco.upv.es', 'jviltor2@teleco.upv.es', 'jvmorcal@teleco.upv.es', 'jvolmalb@teleco.upv.es', 'klaskev@teleco.upv.es', 'lkwiatk@teleco.upv.es', 'lsanrub@teleco.upv.es', 'maamogam@teleco.upv.es', 'mastoica@teleco.upv.es', 'mblamar@etsinf.upv.es', 'mcarber@teleco.upv.es', 'mcebsie@teleco.upv.es', 'mfordom@teleco.upv.es', 'mgardia@arq.upv.es', 'mivados@teleco.upv.es', 'mrmatnot@teleco.upv.es', 'mvilpra@teleco.upv.es', 'nchudic@teleco.upv.es', 'ngomtro@teleco.upv.es', 'nherrub@teleco.upv.es', 'nllosor@teleco.upv.es', 'nterala@teleco.upv.es', 'oanda@teleco.upv.es', 'pbosram@teleco.upv.es', 'pdomzur@teleco.upv.es', 'pferrui@teleco.upv.es', 'pgarmar5@teleco.upv.es', 'pmasdel@teleco.upv.es', 'pmatbol@teleco.upv.es', 'pmiqmol@teleco.upv.es', 'ppalmed@teleco.upv.es', 'psegmon@teleco.upv.es', 'pvilagu@teleco.upv.es', 'rfguelop@teleco.upv.es', 'rjimalb@etsii.upv.es', 'rlosbes@teleco.upv.es', 'rrieagu@teleco.upv.es', 'rsissan@teleco.upv.es', 'sdiamen@teleco.upv.es', 'skashen@teleco.upv.es', 'slin3@teleco.upv.es', 'solilop@teleco.upv.es', 'spuerob@teleco.upv.es', 'sripcig@teleco.upv.es', 'sruiper@teleco.upv.es', 'storram@teleco.upv.es', 'tstevla@teleco.upv.es', 'varonsan@teleco.upv.es', 'vatorcha@teleco.upv.es', 'vmelluz@teleco.upv.es', 'vmonrib@teleco.upv.es', 'vpercol@teleco.upv.es', 'vzarher@teleco.upv.es', 'xblagon@teleco.upv.es', 'xhu2@teleco.upv.es', 'xpallop@teleco.upv.es', 'ytarrui@teleco.upv.es', 'ztraagu@arq.upv.es']

In [4]:
#print(tabla)

In [5]:
def procesa_csv(csv_filename,notas_limpias_dir):

    nombre_columna=os.path.basename(csv_filename).replace(".csv","")
    print(nombre_columna)
    df=pd.read_csv(csv_filename)
    df2=df[ df['email'].notna()]
    df2.index=df2.email
    nameout=os.path.join(notas_limpias_dir, os.path.basename(csv_filename))
    df3=df2[['score','max_score','email']]
    df3['DNI']=""
    for index, row in df.iterrows():
        if row['email'] in tabla:
            row['DNI']=tabla[row['email']]
        else:
            print("NO en la lista:", row['email'])
    #print(">>>>>>>>>>>>>>>>>>")
    #print(df3['email'])
    #print(">>>>>>>>>>>>>>>>>>")
    #df3=df3[df3['email'].str.contains('upv.es', case=False, na=False)]
    print(len(df3))
    #df3['DNI']=dflista[df3['email']]
    #df3['score']=df3['score'].fillna(0)
    df3['score'].fillna(0)
    df3[nombre_columna]=10*df3['score']/df3['max_score']
    df3[nombre_columna] = df3[nombre_columna].round(0).astype('int')
    df4=df3[['DNI',nombre_columna]]
    df4.to_csv(nameout,header=True,index=False,sep=';')
    df3.to_csv("kk.csv",header=True,index=False,sep=';')
    return df4 

def procesa_csv2(csv_filename,notas_limpias_dir):

    nombre_columna=os.path.basename(csv_filename).replace(".csv","")
    print(nombre_columna)
    df=pd.read_csv(csv_filename)
    df2=df[ df['email'].notna()]
    df2.index=df2.email
    nameout=os.path.join(notas_limpias_dir, os.path.basename(csv_filename))
    df3=df2[['score','max_score','email']]
    df3['score'].fillna(0)
    
    alumnos=[]
    for index, row in df3.iterrows():
        alumno={}
        if row['email'] in tabla:
#            if "allovil2" in row['email']:
#                print("allovil2 found")
            alumno['DNI']=tabla[row['email']]
            alumno[nombre_columna]=int(round(row['score']/(0.0001+row['max_score'])*10))
            alumnos.append(alumno)
        else:
            print("NO en la lista:", row['email'])

    #print(alumnos)
   
    df4=pd.DataFrame(alumnos)
    #print(df4)
    df4.to_csv(nameout,header=True,index=False,sep=';')
    
    return df4

In [6]:
ficheros =glob.glob(notasdir+"/*.csv")
print(len(ficheros), " ficheros")

21  ficheros

In [7]:
for f in ficheros:
    print(f)
    a=procesa_csv2(f,notas_limpias_dir)

/home/profesor/Curso/notas/P2-1-pre.csv
P2-1-pre
/home/profesor/Curso/notas/P0-TRX_Digital.csv
P0-TRX_Digital
/home/profesor/Curso/notas/autonomos-PWM.csv
autonomos-PWM
/home/profesor/Curso/notas/P0-2.csv
P0-2
/home/profesor/Curso/notas/P1-4.csv
P1-4
/home/profesor/Curso/notas/P0-4.csv
P0-4
/home/profesor/Curso/notas/P2-1.csv
P2-1
/home/profesor/Curso/notas/P1-3.csv
P1-3
/home/profesor/Curso/notas/P0-3.csv
P0-3
/home/profesor/Curso/notas/P1-3b__RCX_Digital.csv
P1-3b__RCX_Digital
/home/profesor/Curso/notas/autonomos-ReceptorDigitalCompleto.csv
autonomos-ReceptorDigitalCompleto
/home/profesor/Curso/notas/P0-5.csv
P0-5
/home/profesor/Curso/notas/P1-2.csv
P1-2
/home/profesor/Curso/notas/P1-4b__RCX_Digital2.csv
P1-4b__RCX_Digital2
/home/profesor/Curso/notas/P1-1.csv
P1-1
/home/profesor/Curso/notas/P1-3_final.csv
P1-3_final
/home/profesor/Curso/notas/autonomos-multiplex_temporal.csv
autonomos-multiplex_temporal
/home/profesor/Curso/notas/autonomos-crossfade.csv
autonomos-crossfade
/home/profesor/Curso/notas/P2-2.csv
P2-2
/home/profesor/Curso/notas/P1-3_previa.csv
P1-3_previa
/home/profesor/Curso/notas/P2-3.csv
P2-3

In [8]:
   a.head()

         DNI  P2-3
0   44534656    10
1  P63662865    10
2   23944190    10
3   53761214    10
4   24529124    10

In [9]:
f=os.path.join(notasdir,'P0-2.csv')
procesa_csv2(f,notas_limpias_dir)

P0-2

           DNI  P0-2
0     44534656    10
1    P63662865     8
2     23944190     9
3     53761214     8
4     24529124    10
5     73671761     9
6     49435075     7
7     26630518     0
8     23855955     0
9     10250974    10
10    23916286    10
11   P30590824     6
12    53893449    10
13      Y57255     8
14    53877538     9
15    X9896872    10
16    49231824    10
17    20239067     0
18    49233477    10
19    54014371     9
20    49179403     8
21    Z1440566     7
22    24522399     9
23    26661022     9
24    23886851    10
25    23326127     9
26    23943265     0
27    47430733     9
28    35607448     9
29    16816851     8
30    21806094     9
31    54526921    10
32  P652282437    10
33    Y1712772     0
34    49353615    10
35    23940978     9
36    54423947    10
37    78769587     8
38    44922246     9
39    54775152     9